# Generated by Django 2.1.5 on 2019-02-09 15:49

import datetime
from django.db import migrations, models
import picture.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('pic_name', models.CharField(default='', max_length=255, verbose_name='pic_name')),
                ('path', models.ImageField(upload_to=picture.models.user_directory_path, verbose_name='path')),
                ('category', models.CharField(default='default', max_length=100, verbose_name='category')),
                ('pic_size', models.CharField(default='', max_length=20, verbose_name='pic_size')),
                ('upload_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
