# Generated by Django 2.1.5 on 2019-01-26 08:33

import datetime
from django.db import migrations, models
import picture.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default='', verbose_name='user_id')),
                ('category', models.CharField(default='default', max_length=100, verbose_name='类别')),
                ('image', models.ImageField(upload_to=picture.models.user_directory_path, verbose_name='图片')),
                ('upload_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
