# Generated by Django 2.1.5 on 2019-01-26 09:19

from django.db import migrations, models
import picture.models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='pic_size',
            field=models.CharField(default='', max_length=20, verbose_name='pic_size'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='category',
            field=models.CharField(default='default', max_length=100, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=picture.models.user_directory_path, verbose_name='picture'),
        ),
    ]
