# Generated by Django 2.1.5 on 2019-01-24 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picture.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='date',
            new_name='upload_date',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='title',
        ),
        migrations.AddField(
            model_name='picture',
            name='category',
            field=models.CharField(blank=True, default='default', max_length=100, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='picture',
            name='pic_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='图片名'),
        ),
        migrations.AddField(
            model_name='picture',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='picture', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, upload_to=picture.models.user_directory_path, verbose_name='图片'),
        ),
    ]
