# Generated by Django 2.1.5 on 2019-01-26 10:07

from django.db import migrations, models
import picture.models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_auto_20190126_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='image',
        ),
        migrations.AddField(
            model_name='picture',
            name='path',
            field=models.ImageField(default='', upload_to=picture.models.user_directory_path, verbose_name='path'),
        ),
        migrations.AddField(
            model_name='picture',
            name='pic_name',
            field=models.CharField(default='', max_length=20, verbose_name='pic_name'),
        ),
    ]
