# Generated by Django 2.1.5 on 2019-01-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_auto_20190126_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pic_name',
            field=models.CharField(default='', max_length=255, verbose_name='pic_name'),
        ),
    ]
