# Generated by Django 2.1.5 on 2019-02-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_auto_20190126_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='user_id',
            field=models.IntegerField(verbose_name='user_id'),
        ),
    ]
