# Generated by Django 2.1.5 on 2019-02-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SVMModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, verbose_name='model_name')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='create_time')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='update_time')),
                ('train_num', models.IntegerField(default=0, verbose_name='train_num')),
                ('accuracy_score', models.FloatField(default=0, max_length=100, verbose_name='accuracy_score')),
                ('C', models.FloatField(max_length=50, verbose_name='C')),
                ('kernel', models.CharField(max_length=50, verbose_name='kernel')),
                ('pic_size', models.CharField(max_length=50, verbose_name='pic_size')),
                ('orientations', models.CharField(max_length=50, verbose_name='orientations')),
                ('pixels_per_cell', models.CharField(max_length=50, verbose_name='pixels_per_cell')),
                ('cells_per_block', models.CharField(max_length=50, verbose_name='cells_per_block')),
                ('is_color', models.BooleanField(verbose_name='is_color ')),
                ('is_standard', models.BooleanField(verbose_name='is_standard')),
            ],
        ),
    ]
