# Generated by Django 2.1.5 on 2019-02-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTrainLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('train_time', models.DateTimeField(auto_now_add=True, verbose_name='train_time')),
                ('model_id', models.IntegerField(verbose_name='model_id')),
                ('accuracy_score', models.FloatField(default=0, max_length=100, verbose_name='accuracy_score')),
                ('train_category_positive', models.CharField(max_length=100, verbose_name='train_category_positive')),
                ('positive_num', models.IntegerField(verbose_name='positive_num')),
                ('train_category_negative', models.CharField(max_length=100, verbose_name='train_category_negative')),
                ('negative_num', models.IntegerField(verbose_name='negative_num')),
                ('validation_size', models.FloatField(verbose_name='validation_size')),
            ],
        ),
        migrations.CreateModel(
            name='SVMModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('model_name', models.CharField(max_length=50, verbose_name='model_name')),
                ('comment', models.TextField(blank=True, max_length=255, verbose_name='comment')),
                ('train_num', models.IntegerField(default=0, verbose_name='train_num')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='update_time')),
                ('recently_accuracy_score', models.FloatField(default=0, max_length=100, verbose_name='recently_accuracy_score')),
                ('C', models.FloatField(max_length=50, verbose_name='C')),
                ('kernel', models.CharField(choices=[('sigmoid', 'sigmoid'), ('rbf', 'rbf'), ('poly', 'poly'), ('linear', 'linear')], max_length=50, verbose_name='kernel')),
                ('is_standard', models.BooleanField(verbose_name='is_standard')),
                ('is_color', models.BooleanField(verbose_name='is_color')),
                ('pic_size', models.CharField(max_length=50, verbose_name='pic_size')),
                ('orientations', models.IntegerField(verbose_name='orientations')),
                ('pixels_per_cell', models.CharField(max_length=50, verbose_name='pixels_per_cell')),
                ('cells_per_block', models.CharField(max_length=50, verbose_name='cells_per_block')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='create_time')),
                ('ensemble_learning', models.CharField(choices=[('BaggingClassifier', 'BaggingClassifier'), ('AdaBoostClassifier', 'AdaBoostClassifier'), ('None', 'None')], default='None', max_length=50, verbose_name='ensemble_learning')),
                ('n_estimators', models.IntegerField(default=0, verbose_name='n_estimators')),
            ],
        ),
    ]
