# Generated by Django 2.1.5 on 2019-02-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svmmodel',
            name='ensemble_learning',
            field=models.CharField(choices=[('sigmoid', 'sigmoid'), ('rbf', 'rbf'), ('poly', 'poly'), ('linear', 'linear')], default=None, max_length=50, verbose_name='ensemble_learning'),
        ),
        migrations.AlterField(
            model_name='svmmodel',
            name='n_estimators',
            field=models.IntegerField(default=0, verbose_name='n_estimators'),
        ),
    ]
