# Generated by Django 2.1.5 on 2019-02-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_modeltrainlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltrainlog',
            name='validation_size',
            field=models.FloatField(verbose_name='validation_size'),
        ),
    ]
