# Generated by Django 2.1.5 on 2019-02-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0003_auto_20190208_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svmmodel',
            name='ensemble_learning',
            field=models.CharField(choices=[('BaggingClassifier', 'BaggingClassifier'), ('AdaBoostClassifier', 'AdaBoostClassifier'), ('None', 'None')], default='None', max_length=50, verbose_name='ensemble_learning'),
        ),
    ]
