# Generated by Django 2.1.5 on 2019-02-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0003_auto_20190207_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svmmodel',
            name='accuracy_score',
        ),
        migrations.AddField(
            model_name='svmmodel',
            name='recently_accuracy_score',
            field=models.FloatField(default=0, max_length=100, verbose_name='recently_accuracy_score'),
        ),
        migrations.AlterField(
            model_name='svmmodel',
            name='is_color',
            field=models.BooleanField(verbose_name='is_color'),
        ),
        migrations.AlterField(
            model_name='svmmodel',
            name='kernel',
            field=models.CharField(choices=[('sigmoid', 'sigmoid'), ('rbf', 'rbf'), ('poly', 'poly'), ('linear', 'linear')], max_length=50, verbose_name='kernel'),
        ),
    ]
