# Generated by Django 2.1.5 on 2019-02-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0004_auto_20190208_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svmmodel',
            name='orientations',
            field=models.IntegerField(max_length=50, verbose_name='orientations'),
        ),
    ]
