# Generated by Django 2.1.5 on 2019-02-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0004_auto_20190208_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='svmmodel',
            name='comment',
            field=models.TextField(default='', verbose_name='comment'),
        ),
    ]
