# Generated by Django 2.1.5 on 2019-02-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0005_svmmodel_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svmmodel',
            name='comment',
            field=models.CharField(default='', max_length=255, verbose_name='comment'),
        ),
    ]
