# Generated by Django 2.1.5 on 2019-02-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0006_auto_20190221_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svmmodel',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='comment'),
        ),
    ]
